apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config

data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: devmart_auth

  MYSQL_USER: root

  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"