apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-container
          image: devmart-platform-auth-service:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000